In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head(15)

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.sample(5)

review education purchased
19     Poor        PG       Yes
29  Average        UG       Yes
16     Poor        UG       Yes
32  Average        UG       Yes
13  Average    School        No

all categorical columns

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [12]:
X_train

review education
38     Good    School
8   Average        UG
13  Average    School
2      Good        PG
26     Poor        PG
48     Good        UG
1      Poor        UG
34  Average    School
39     Poor        PG
32  Average        UG
18     Good    School
9      Good        UG
49     Good        UG
42     Good        PG
30  Average        UG
21  Average        PG
41     Good        PG
10     Good        UG
16     Poor        UG
5   Average    School
14     Poor        PG
35     Poor    School
11     Good        UG
24  Average        PG
45     Poor        PG
46     Poor        PG
6      Good    School
37  Average        PG
31     Poor    School
36     Good        UG
33     Good        PG
17     Poor        UG
12     Poor    School
44  Average        UG
47     Good        PG
3      Good        PG
27     Poor        PG
15     Poor        UG
29  Average        UG
25     Good    School

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [13]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
X_train = oe.transform(X_train)

In [15]:
X_train

array([[2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
X_train

array([[2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.]])

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

In [20]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [22]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [23]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0])